apiVersion: v1
kind: Service
metadata:
  name: nginx-service-external
spec:
  type: LoadBalancer
  clusterIP: 10.97.0.1
  selector:
    app: nginx-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127